export const PERMISSIONS = [
  'user:read',
  'user:write',
  'org:read',
  'org:write',
  'dossier:read',
  'dossier:write',
  'dossier:review',
  'dossier:export',
  'dossier:timeline',
  'catalog:read',
  'simulation:run',
  'simulation:read',
  'guide:batch',
  'compliance:read',
  'compliance:write',
  'audit:read',
  'dashboard:read',
  'report:export',
] as const;

export const ROLE_PERMISSION_MAP: Record<string, readonly string[]> = {
  admin: PERMISSIONS,
  juridico: [
    'dossier:read',
    'dossier:write',
    'dossier:review',
    'dossier:export',
    'dossier:timeline',
    'catalog:read',
    'user:read',
    'org:read',
  ],
  faturamento: [
    'simulation:run',
    'dossier:read',
    'guide:batch',
    'user:read',
    'org:read',
  ],
  compliance: [
    'compliance:read',
    'compliance:write',
    'dossier:read',
    'catalog:read',
    'user:read',
    'org:read',
  ],
  auditoria: [
    'dossier:read',
    'catalog:read',
    'audit:read',
    'simulation:read',
    'user:read',
    'org:read',
  ],
  diretoria: [
    'dashboard:read',
    'report:export',
    'dossier:read',
    'catalog:read',
    'org:read',
  ],
  somente_leitura: [
    'dossier:read',
    'catalog:read',
    'simulation:read',
    'org:read',
    'user:read',
  ],
};

export const ROLE_NAMES: Record<string, string> = {
  admin: 'Administrador',
  juridico: 'Jurídico',
  faturamento: 'Faturamento',
  compliance: 'Compliance',
  auditoria: 'Auditoria',
  diretoria: 'Diretoria',
  somente_leitura: 'Somente leitura',
};
